### ISSUE TITLE
Example Using Streams

### ISSUE THREAD

**Issue by ArcherEmiya05** [aNNiMON/Android-Java-8-Stream-Example#3]
Hello this is not an issue at all but I'm not familiar with Java 8 Stream and I cant use that API in my Android 
 app because of SDK incompatibility. Anyway could you help me or give me the correct algorithm for checking if a List containing an Object with some properties like id is equal to a value of string x that returns a boolean value. This is to check first if the incoming object with id is already an existing object  before adding it to List<Object>. Sorry for the inconvenience and Thanks in advance.

**Comment by aNNiMON** [comment]
Hello, answered [here](https://github.com/aNNiMON/Lightweight-Stream-API/issues/166#issuecomment-396191639).
